name: bridge_native
description: Neos
version: 1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: vn.educa.bridge
        pluginClass: Pigeon
      ios:
        pluginClass: FLTPigeon

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  pigeon: any
  injectable_generator: any
  build_runner: any
  built_value_generator: any

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
